### ISSUE TITLE
Layout quebrando no mobile

### ISSUE THREAD

**Issue by alexcmgit** [JoaoSCoelho/GameMath#1]
![Screenshot_20200724-032001_Chrome](https://user-images.githubusercontent.com/51419598/88365513-ab216800-cd5c-11ea-8ce9-4735f45b3892.jpg)
![Screenshot_20200724-032013_Chrome](https://user-images.githubusercontent.com/51419598/88365516-aceb2b80-cd5c-11ea-9661-811b0707f070.jpg) 

Após certa quantidade de score o botões quebram e confundem, fazendo inevitável o game over, ahahah, um jogo super criativo e interessante, parabéns, só tem esse probleminha que com acredito que pode ser resolvido com:
```css
elemento {
  flex-wrap: nowrap;
}
```

**Comment by JoaoSCoelho** [comment]
> Após certa quantidade de score o botões quebram e confundem, fazendo inevitável o game over, ahahah, um jogo super criativo e interessante, parabéns, só tem esse probleminha que com acredito que pode ser resolvido com:

Opa, muito obrigado pelo aviso, eu já havia visto esse problema antes, mas não consegui pensar em alguma maneira de resolver... Para isso eu colori os números que devem ser somados de azul para melhorar para o jogador, mas mesmo assim continua sendo um impecílio que atrapalha os jogadores que utilizam telas menores.

Eu testei sua sugestão de solução, e infelismente continuou saltando a linha, vou testar novos métodos para corrigir isso, qualquer novidade eu aviso.

Se desejar clonar o repositório para tentar resolver isso, fique a vontade, qualquer ajuda é bem vinda.

Obrigado, 
João Victor

**Comment by alexcmgit** [comment]
Certo! Vou tentar resolver e enviar a pull request

**Comment by alexcmgit** [comment]
Acabei de editar o código, mas pelo visto não há solução aparente dentro do código, visto que ele não está utilizando FlexBox, e sim \<br> para gerenciar o Layout das opções. Mas tudo bem, em breve vou escrever um jogo inspirado neste seu, e vou tentar consertar este pequeno errinho, vou fechar a Issue
